Repository EZZ00M/EZZ00M-client, pull requests merged in 2025-01, with the labels that each got.

#6 docs: readme 업데이트
  README.md
Labels: docs

#7 feat: netlify 배포를 위한 파일 추가
  netlify.toml
  public/_redirects
Labels: feat

#8 docs: PR 템플릿 생성
  .github/pull_request_template.md
Labels: docs

#9 feat: toml 파일 변경
  netlify.toml
Labels: fix

#10 fix: 의존성 재설치
  package-lock.json
Labels: fix

#12 merge: dev to main
  .github/pull_request_template.md
  README.md
  netlify.toml
  package-lock.json
  public/_redirects
Labels: deploy

#17 fix: 데이터 구조 수정
  src/components/DragBox/DragBox.jsx
Labels: 🐞 bug fix

#20 merge: dev to main
  src/components/DragBox/DragBox.jsx
  src/components/DragBox/DragBox.style.jsx
  src/components/DragBox/StateComponent/AnalysisCompleteState.jsx
  src/components/DragBox/StateComponent/FileSelectedState.jsx
  src/components/Footer/Footer.style.jsx
  src/components/Header/Header.jsx
  src/components/Header/Header.style.jsx
  src/components/Modal/Modal.jsx
  src/pages/ZoomAnalyzePage.jsx
  src/pages/ZoomAnalyzePage.style.jsx
Labels: 🌏 deploy

#21 feat: 구글 애널리틱스 코드 추가
  index.html
Labels: 💫 feature

#23 modify: 구글 애널리스틱 수정
  index.html
Labels: 🔧 fix

#24 docs: README.md 수정
  README.md
Labels: 📃 docs

#25 merge: dev to main
  README.md
  index.html
Labels: 🌏 deploy

#26 feat: 모바일 반응형 적용
  index.html
  src/components/DragBox/DragBox.jsx
  src/components/DragBox/DragBox.style.jsx
  src/components/DragBox/StateComponent/EmptyState.jsx
  src/components/Explanation/Explanation.jsx
  src/components/Explanation/Explanation.style.jsx
  src/components/Header/Header.jsx
  src/components/Header/Header.style.jsx
  src/components/Modal/Modal.style.jsx
  src/pages/ZoomAnalyzePage.jsx
  src/pages/ZoomAnalyzePage.style.jsx
  src/styles/index.js
  src/styles/mediaQueries.js
Labels: 💫 feature

#27 merge: dev to main
  index.html
  src/components/DragBox/DragBox.jsx
  src/components/DragBox/DragBox.style.jsx
  src/components/DragBox/StateComponent/EmptyState.jsx
  src/components/Explanation/Explanation.jsx
  src/components/Explanation/Explanation.style.jsx
  src/components/Header/Header.jsx
  src/components/Header/Header.style.jsx
  src/components/Modal/Modal.style.jsx
  src/pages/ZoomAnalyzePage.jsx
  src/pages/ZoomAnalyzePage.style.jsx
  src/styles/index.js
  src/styles/mediaQueries.js
Labels: 🌏 deploy
